/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package fibonacci.test

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class Sample() {
    fun sum(a: Int, b: Int): Int {
        return a + b
    }
}

class AppTest {
    private val testSample: Sample = Sample()

    @Test
    fun appHasAGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }

    @Test
    fun testSum() {
        val expected = 42
        assertEquals(expected, testSample.sum(40, 2))
    }
}
